---############
---
local utils = require("utils.utils")

local function minmax(board, depth, is_maximizing)

end
function init(self)
    local mini_board = {}
    self.boards = {}

    for i = 1, 3 do
        mini_board[i] = {}
        for j = 1, 3 do
            mini_board[i][j] = {}
        end
    end

    for i = 1, 3 do
        self.boards[i] = {}
        for j = 1, 3 do
            self.boards[i][j] = mini_board
        end
    end
end
